// <auto-generated />
namespace Cupr.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cupr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cupr));
        
        string IMigrationMetadata.Id
        {
            get { return "202002140451111_cupr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
